"""Add password column to subscription

Revision ID: 05b10d728c79
Revises: 9454eee5953d
Create Date: 2026-04-27 21:00:42.114543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05b10d728c79'
down_revision: Union[str, Sequence[str], None] = '9454eee5953d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panel', sa.Column('password', sa.String(length=255), nullable=False))
    op.drop_column('panel', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panel', sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False))
    op.drop_column('panel', 'password')
    # ### end Alembic commands ###
