"""add sub_level and remove is_disposable

Revision ID: 273feba0b698
Revises: dcd25ce1f0f6
Create Date: 2026-07-17 18:19:55.484357

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '273feba0b698'
down_revision: Union[str, Sequence[str], None] = 'dcd25ce1f0f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promocode', sa.Column('sub_level', sa.Integer(), nullable=True))
    op.drop_column('promocode', 'is_disposable')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promocode', sa.Column('is_disposable', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('promocode', 'sub_level')
    # ### end Alembic commands ###
