"""Add port in panel

Revision ID: 40b745931f4d
Revises: f19fc7c28a2b
Create Date: 2026-05-07 13:42:35.999958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40b745931f4d'
down_revision: Union[str, Sequence[str], None] = 'f19fc7c28a2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panel', sa.Column('port', sa.String(length=10), nullable=True))
    op.drop_constraint(op.f('subscription_panels_subscription_id_fkey'), 'subscription_panels', type_='foreignkey')
    op.create_foreign_key(None, 'subscription_panels', 'subscription', ['subscription_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscription_panels', type_='foreignkey')
    op.create_foreign_key(op.f('subscription_panels_subscription_id_fkey'), 'subscription_panels', 'subscription', ['subscription_id'], ['id'], ondelete='CASCADE')
    op.drop_column('panel', 'port')
    # ### end Alembic commands ###
