"""Add relation user and promo  model

Revision ID: 4dbb6eb45979
Revises: 429731b6986d
Create Date: 2026-07-03 14:20:41.922254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dbb6eb45979'
down_revision: Union[str, Sequence[str], None] = '429731b6986d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promocode', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_promocode_user_id'), 'promocode', ['user_id'], unique=False)
    op.create_foreign_key(None, 'promocode', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promocode', type_='foreignkey')
    op.drop_index(op.f('ix_promocode_user_id'), table_name='promocode')
    op.drop_column('promocode', 'user_id')
    # ### end Alembic commands ###
