"""add sub_id in promocode model

Revision ID: 8757a50de3da
Revises: 004b96863124
Create Date: 2026-07-17 23:22:41.673219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8757a50de3da'
down_revision: Union[str, Sequence[str], None] = '004b96863124'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('promocode', sa.Column('sub_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_promocode_sub_id'), 'promocode', ['sub_id'], unique=False)
    op.create_foreign_key(None, 'promocode', 'subscription', ['sub_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'promocode', type_='foreignkey')
    op.drop_index(op.f('ix_promocode_sub_id'), table_name='promocode')
    op.drop_column('promocode', 'sub_id')
    # ### end Alembic commands ###
