"""Add cookie column to panel

Revision ID: a8cdccb57c81
Revises: 05b10d728c79
Create Date: 2026-04-27 21:38:34.692019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8cdccb57c81'
down_revision: Union[str, Sequence[str], None] = '05b10d728c79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panel', sa.Column('cookie', sa.String(length=750), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panel', 'cookie')
    # ### end Alembic commands ###
