"""add ip, api_token, description panel

Revision ID: ff5bcb22878c
Revises: 62b9ddc20ec1
Create Date: 2026-09-25 18:40:23.716391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff5bcb22878c'
down_revision: Union[str, Sequence[str], None] = '62b9ddc20ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panel', sa.Column('ip', sa.String(length=16), nullable=False))
    op.add_column('panel', sa.Column('api_token', sa.String(length=50), nullable=False))
    op.add_column('panel', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_column('panel', 'cookie')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panel', sa.Column('cookie', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('panel', 'description')
    op.drop_column('panel', 'api_token')
    op.drop_column('panel', 'ip')
    # ### end Alembic commands ###
